import { AYAVA_ORGANIZATION_ID } from '../../prisma/seed/ids'
import { expectDbRejection, prisma, uniqueSuffix } from './helpers'

afterAll(() => prisma.$disconnect())

const EXPECTED_TABLES = [
  'organizations',
  'users',
  'roles',
  'permissions',
  'role_permissions',
  'user_roles',
  'departments',
  'teams',
  'positions',
  'interns',
  'intern_profiles',
  'emergency_contacts',
  // Phase 03: intern management and onboarding
  'onboardings',
  'onboarding_templates',
  'onboarding_template_items',
  'policies',
  'document_acknowledgements',
  'intern_lifecycle_events',
  'code_counters',
  // Phase 04: work management
  'task_checklist_items',
  'task_dependencies',
  'task_comment_mentions',
  'task_time_entries',
  'project_attachments',
  // Phase 05: HR operations
  'attendance_breaks',
  'leave_balances',
  'document_types',
  'holidays',
  'hr_requests',
  'hr_request_comments',
  'hr_request_attachments',
  'offboarding_checklists',
  'offboarding_items',
  'internships',
  'internship_documents',
  'onboarding_items',
  'projects',
  'project_members',
  'milestones',
  'tasks',
  'task_assignees',
  'task_comments',
  'task_attachments',
  'task_submissions',
  'submission_versions',
  'attendance',
  'attendance_corrections',
  'leave_types',
  'leave_requests',
  'courses',
  'lessons',
  'quizzes',
  'quiz_attempts',
  'learning_progress',
  'meetings',
  'calendar_events',
  'feedback',
  'weekly_checkins',
  'performance_reviews',
  'announcements',
  'notifications',
  'channels',
  'messages',
  'certificates',
  'certificate_verifications',
  'ai_conversations',
  'ai_messages',
  'knowledge_documents',
  'audit_logs',
  'settings',
  'user_invitations',
  'user_sessions',
  'rate_limit_buckets',
]

describe('schema from migrations', () => {
  it('creates every foundation table', async () => {
    const rows = await prisma.$queryRaw<{ table_name: string }[]>`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = current_schema() AND table_type = 'BASE TABLE' AND table_name <> '_prisma_migrations'`
    expect(rows.map((row) => row.table_name).sort()).toEqual([...EXPECTED_TABLES].sort())
  })

  it('does not store passwords anywhere', async () => {
    const rows = await prisma.$queryRaw<{ column_name: string }[]>`
      SELECT column_name FROM information_schema.columns
      WHERE table_schema = current_schema() AND column_name ILIKE '%password%'`
    expect(rows).toEqual([])
  })

  it('enables row-level security on every table', async () => {
    const rows = await prisma.$queryRaw<{ relname: string }[]>`
      SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = current_schema() AND c.relkind = 'r'
        AND c.relname <> '_prisma_migrations' AND NOT c.relrowsecurity`
    expect(rows).toEqual([])
  })

  it('uses UUID primary keys generated by the database', async () => {
    const rows = await prisma.$queryRaw<{ table_name: string }[]>`
      SELECT c.table_name FROM information_schema.columns c
      WHERE c.table_schema = current_schema() AND c.column_name = 'id'
        AND c.table_name <> '_prisma_migrations'
        AND (c.data_type <> 'uuid' OR c.column_default IS NULL OR c.column_default NOT LIKE 'gen_random_uuid%')`
    expect(rows).toEqual([])
  })

  it('indexes foreign keys used for tenant and ownership lookups', async () => {
    const rows = await prisma.$queryRaw<{ indexname: string }[]>`
      SELECT indexname FROM pg_indexes WHERE schemaname = current_schema()`
    const names = rows.map((row) => row.indexname)
    for (const expected of [
      'users_organization_id_email_key',
      'tasks_organization_id_status_idx',
      'tasks_organization_id_due_date_idx',
      'interns_manager_id_idx',
      'interns_mentor_id_idx',
      'certificates_certificate_number_key',
      'certificate_verifications_verification_code_key',
      'audit_logs_organization_id_created_at_idx',
    ]) {
      expect(names).toContain(expected)
    }
  })
})

describe('integrity constraints', () => {
  it('rejects performance scores outside 1–5', async () => {
    const intern = await prisma.intern.findFirstOrThrow({ where: { organization_id: AYAVA_ORGANIZATION_ID } })
    const reviewer = await prisma.user.findFirstOrThrow({ where: { email: 'manager@ayavacreatives.com' } })
    await expectDbRejection(
      prisma.performanceReview.create({
        data: {
          organization_id: AYAVA_ORGANIZATION_ID,
          intern_id: intern.id,
          reviewer_id: reviewer.id,
          review_period_start: new Date('2026-01-01'),
          review_period_end: new Date('2026-03-31'),
          quality: 6,
        },
      }),
      /performance_reviews_scores_chk/,
    )
  })

  it('rejects leave that ends before it starts', async () => {
    const user = await prisma.user.findFirstOrThrow({ where: { email: 'intern@ayavacreatives.com' } })
    const leaveType = await prisma.leaveType.findFirstOrThrow({ where: { organization_id: AYAVA_ORGANIZATION_ID } })
    await expectDbRejection(
      prisma.leaveRequest.create({
        data: {
          organization_id: AYAVA_ORGANIZATION_ID,
          user_id: user.id,
          leave_type_id: leaveType.id,
          start_date: new Date('2026-05-10'),
          end_date: new Date('2026-05-01'),
        },
      }),
      /leave_requests_dates_chk/,
    )
  })

  it('requires lowercase, unique emails per organization', async () => {
    await expectDbRejection(
      prisma.user.create({
        data: { organization_id: AYAVA_ORGANIZATION_ID, email: 'Mixed@Case.com', first_name: 'A', last_name: 'B' },
      }),
      /users_email_lowercase_chk/,
    )
    await expectDbRejection(
      prisma.user.create({
        data: {
          organization_id: AYAVA_ORGANIZATION_ID,
          email: 'admin@ayavacreatives.com',
          first_name: 'A',
          last_name: 'B',
        },
      }),
      /Unique constraint/,
    )
  })

  it('allows only one attendance record per person per day', async () => {
    const user = await prisma.user.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        email: `att-${uniqueSuffix()}@test.dev`,
        first_name: 'A',
        last_name: 'B',
      },
    })
    const day = new Date('2026-06-01')
    await prisma.attendance.create({ data: { organization_id: AYAVA_ORGANIZATION_ID, user_id: user.id, date: day } })
    await expectDbRejection(
      prisma.attendance.create({ data: { organization_id: AYAVA_ORGANIZATION_ID, user_id: user.id, date: day } }),
      /Unique constraint/,
    )
  })
})

describe('referential actions protect history', () => {
  it('does not let a user with attendance history be hard-deleted', async () => {
    const user = await prisma.user.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        email: `hist-${uniqueSuffix()}@test.dev`,
        first_name: 'A',
        last_name: 'B',
      },
    })
    await prisma.attendance.create({
      data: { organization_id: AYAVA_ORGANIZATION_ID, user_id: user.id, date: new Date('2026-06-02') },
    })
    await expectDbRejection(
      prisma.user.delete({ where: { id: user.id } }),
      /violates RESTRICT setting|Foreign key constraint/,
    )
  })

  it('keeps audit logs when the actor is removed', async () => {
    const user = await prisma.user.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        email: `audit-${uniqueSuffix()}@test.dev`,
        first_name: 'A',
        last_name: 'B',
      },
    })
    const log = await prisma.auditLog.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        actor_user_id: user.id,
        action: 'test.done',
        resource_type: 'test',
      },
    })
    await prisma.user.delete({ where: { id: user.id } })
    const survived = await prisma.auditLog.findUniqueOrThrow({ where: { id: log.id } })
    expect(survived.actor_user_id).toBeNull()
  })

  it('removes pure child rows with their task', async () => {
    const creator = await prisma.user.findFirstOrThrow({ where: { email: 'manager@ayavacreatives.com' } })
    const task = await prisma.task.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        title: 'Temporary',
        created_by: creator.id,
        assignees: { create: { user_id: creator.id } },
        comments: { create: { user_id: creator.id, body: 'hi' } },
      },
    })
    await prisma.task.delete({ where: { id: task.id } })
    expect(await prisma.taskAssignee.count({ where: { task_id: task.id } })).toBe(0)
    expect(await prisma.taskComment.count({ where: { task_id: task.id } })).toBe(0)
  })

  it('refuses to delete an organization that owns data', async () => {
    await expectDbRejection(
      prisma.organization.delete({ where: { id: AYAVA_ORGANIZATION_ID } }),
      /violates RESTRICT setting|Foreign key constraint/,
    )
  })
})

describe('Phase 05 HR constraints', () => {
  it('allows one holiday per date and one open break per attendance record', async () => {
    const date = new Date('2031-01-01T00:00:00Z')
    await prisma.holiday.create({ data: { organization_id: AYAVA_ORGANIZATION_ID, date, name: 'Constraint test' } })
    await expectDbRejection(
      prisma.holiday.create({ data: { organization_id: AYAVA_ORGANIZATION_ID, date, name: 'Duplicate' } }),
    )
    const user = await prisma.user.findFirstOrThrow({ where: { email: 'intern@ayavacreatives.com' } })
    const record = await prisma.attendance.create({
      data: {
        organization_id: AYAVA_ORGANIZATION_ID,
        user_id: user.id,
        date: new Date('2031-01-02T00:00:00Z'),
        check_in_at: new Date(),
      },
    })
    await prisma.attendanceBreak.create({ data: { attendance_id: record.id, started_at: new Date() } })
    await expectDbRejection(
      prisma.attendanceBreak.create({ data: { attendance_id: record.id, started_at: new Date() } }),
    )
  })

  it('requires a reason for rejected documents and overridden leave', async () => {
    const doc = await prisma.internshipDocument.findFirstOrThrow({ where: { status: 'VERIFIED' } })
    await expectDbRejection(
      prisma.internshipDocument.update({ where: { id: doc.id }, data: { status: 'REJECTED', rejection_reason: null } }),
    )
    const leave = await prisma.leaveRequest.findFirstOrThrow()
    await expectDbRejection(
      prisma.leaveRequest.update({ where: { id: leave.id }, data: { overlap_override: true, override_reason: null } }),
    )
  })

  it('requires targets for department, team and specific-people announcements', async () => {
    await expectDbRejection(
      prisma.announcement.create({
        data: {
          organization_id: AYAVA_ORGANIZATION_ID,
          title: `Targeted ${uniqueSuffix()}`,
          body: 'x',
          audience: 'SPECIFIC',
          audience_ids: [],
        },
      }),
    )
  })
})
