export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_INVITE: 'users.invite',
  USERS_SUSPEND: 'users.suspend',

  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',

  PERMISSIONS_READ: 'permissions.read',
  PERMISSIONS_MANAGE: 'permissions.manage',

  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',

  DEPARTMENT_READ: 'department.read',
  DEPARTMENT_CREATE: 'department.create',
  DEPARTMENT_UPDATE: 'department.update',
  DEPARTMENT_DELETE: 'department.delete',

  TEAM_READ: 'team.read',
  TEAM_CREATE: 'team.create',
  TEAM_UPDATE: 'team.update',
  TEAM_DELETE: 'team.delete',

  INTERN_READ: 'intern.read',
  INTERN_CREATE: 'intern.create',
  INTERN_UPDATE: 'intern.update',
  INTERN_DELETE: 'intern.delete',
  INTERN_PROFILE_READ: 'intern.profile.read',
  INTERN_PROFILE_UPDATE: 'intern.profile.update',

  INTERNSHIP_READ: 'internship.read',
  INTERNSHIP_CREATE: 'internship.create',
  INTERNSHIP_UPDATE: 'internship.update',
  INTERNSHIP_COMPLETE: 'internship.complete',

  ONBOARDING_READ: 'onboarding.read',
  ONBOARDING_MANAGE: 'onboarding.manage',
  ONBOARDING_COMPLETE: 'onboarding.complete',

  PROJECT_READ: 'project.read',
  PROJECT_CREATE: 'project.create',
  PROJECT_UPDATE: 'project.update',
  PROJECT_DELETE: 'project.delete',
  PROJECT_MANAGE_MEMBERS: 'project.manage_members',

  TASK_READ: 'task.read',
  TASK_CREATE: 'task.create',
  TASK_UPDATE: 'task.update',
  TASK_DELETE: 'task.delete',
  TASK_ASSIGN: 'task.assign',
  TASK_REVIEW: 'task.review',
  TASK_SUBMIT: 'task.submit',

  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_UPDATE: 'attendance.update',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_CORRECTION_REQUEST: 'attendance.correction.request',
  ATTENDANCE_CORRECTION_REVIEW: 'attendance.correction.review',

  LEAVE_READ: 'leave.read',
  LEAVE_REQUEST: 'leave.request',
  LEAVE_CANCEL: 'leave.cancel',
  LEAVE_APPROVE: 'leave.approve',
  LEAVE_REJECT: 'leave.reject',

  DOCUMENT_READ: 'document.read',
  DOCUMENT_UPLOAD: 'document.upload',
  DOCUMENT_DELETE: 'document.delete',
  DOCUMENT_MANAGE: 'document.manage',

  COURSE_READ: 'course.read',
  COURSE_CREATE: 'course.create',
  COURSE_UPDATE: 'course.update',
  COURSE_DELETE: 'course.delete',
  COURSE_PUBLISH: 'course.publish',

  LEARNING_READ: 'learning.read',
  LEARNING_MANAGE: 'learning.manage',

  FEEDBACK_READ: 'feedback.read',
  FEEDBACK_CREATE: 'feedback.create',

  CHECKIN_READ: 'checkin.read',
  CHECKIN_CREATE: 'checkin.create',
  CHECKIN_REVIEW: 'checkin.review',

  PERFORMANCE_READ: 'performance.read',
  PERFORMANCE_CREATE: 'performance.create',
  PERFORMANCE_UPDATE: 'performance.update',
  PERFORMANCE_REVIEW: 'performance.review',

  ANNOUNCEMENT_READ: 'announcement.read',
  ANNOUNCEMENT_CREATE: 'announcement.create',
  ANNOUNCEMENT_UPDATE: 'announcement.update',
  ANNOUNCEMENT_DELETE: 'announcement.delete',

  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_MANAGE: 'notification.manage',

  CALENDAR_READ: 'calendar.read',
  CALENDAR_CREATE: 'calendar.create',
  CALENDAR_UPDATE: 'calendar.update',
  CALENDAR_DELETE: 'calendar.delete',

  CERTIFICATE_READ: 'certificate.read',
  CERTIFICATE_CREATE: 'certificate.create',
  CERTIFICATE_VERIFY: 'certificate.verify',

  ANALYTICS_READ: 'analytics.read',
  AUDIT_LOG_READ: 'audit_log.read',

  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',

  SESSIONS_READ: 'sessions.read',
  SESSIONS_REVOKE: 'sessions.revoke',

  AI_USE: 'ai.use',
  AI_MANAGE: 'ai.manage',

  KNOWLEDGE_READ: 'knowledge.read',
  KNOWLEDGE_MANAGE: 'knowledge.manage',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const SYSTEM_ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'HR',
  'MANAGER',
  'MENTOR',
  'INTERN',
] as const

export type SystemRole = (typeof SYSTEM_ROLES)[number]

export const ROLE_RANK: Record<SystemRole, number> = {
  SUPER_ADMIN: 100,
  ADMIN: 80,
  HR: 60,
  MANAGER: 50,
  MENTOR: 40,
  INTERN: 10,
}

export const SYSTEM_ROLE_DESCRIPTIONS: Record<SystemRole, string> = {
  SUPER_ADMIN: 'System-wide organization administration, security, and configuration.',
  ADMIN: 'Operational administration of users, catalog of work, and settings.',
  HR: 'Internship lifecycle, onboarding, attendance, leave, and people records.',
  MANAGER: 'Assigned intern operations, projects, tasks, and performance.',
  MENTOR: 'Assigned intern guidance, learning progress, and feedback.',
  INTERN: 'Own profile, work, attendance, leave, learning, and announcements.',
}

const P = PERMISSIONS

export const ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  ADMIN: [
    P.USERS_READ,
    P.USERS_CREATE,
    P.USERS_UPDATE,
    P.USERS_INVITE,
    P.USERS_SUSPEND,
    P.ROLES_READ,
    P.PERMISSIONS_READ,
    P.ORGANIZATION_READ,
    P.ORGANIZATION_UPDATE,
    P.DEPARTMENT_READ,
    P.DEPARTMENT_CREATE,
    P.DEPARTMENT_UPDATE,
    P.TEAM_READ,
    P.TEAM_CREATE,
    P.TEAM_UPDATE,
    P.INTERN_READ,
    P.INTERN_CREATE,
    P.INTERN_UPDATE,
    P.INTERN_DELETE,
    P.INTERN_PROFILE_READ,
    P.INTERN_PROFILE_UPDATE,
    P.INTERNSHIP_READ,
    P.INTERNSHIP_CREATE,
    P.INTERNSHIP_UPDATE,
    P.ONBOARDING_READ,
    P.ONBOARDING_MANAGE,
    P.PROJECT_READ,
    P.PROJECT_CREATE,
    P.PROJECT_UPDATE,
    P.PROJECT_DELETE,
    P.PROJECT_MANAGE_MEMBERS,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_UPDATE,
    P.TASK_DELETE,
    P.TASK_ASSIGN,
    P.TASK_REVIEW,
    P.ATTENDANCE_READ,
    P.ATTENDANCE_MANAGE,
    P.LEAVE_READ,
    P.LEAVE_APPROVE,
    P.LEAVE_REJECT,
    P.DOCUMENT_READ,
    P.DOCUMENT_MANAGE,
    P.COURSE_READ,
    P.COURSE_CREATE,
    P.COURSE_UPDATE,
    P.COURSE_PUBLISH,
    P.LEARNING_READ,
    P.LEARNING_MANAGE,
    P.FEEDBACK_READ,
    P.FEEDBACK_CREATE,
    P.CHECKIN_READ,
    P.CHECKIN_REVIEW,
    P.PERFORMANCE_READ,
    P.PERFORMANCE_CREATE,
    P.PERFORMANCE_UPDATE,
    P.PERFORMANCE_REVIEW,
    P.ANNOUNCEMENT_READ,
    P.ANNOUNCEMENT_CREATE,
    P.ANNOUNCEMENT_UPDATE,
    P.ANNOUNCEMENT_DELETE,
    P.NOTIFICATION_READ,
    P.NOTIFICATION_MANAGE,
    P.CALENDAR_READ,
    P.CALENDAR_CREATE,
    P.CALENDAR_UPDATE,
    P.CALENDAR_DELETE,
    P.CERTIFICATE_READ,
    P.CERTIFICATE_CREATE,
    P.ANALYTICS_READ,
    P.AUDIT_LOG_READ,
    P.SETTINGS_READ,
    P.SETTINGS_UPDATE,
    P.SESSIONS_READ,
    P.AI_USE,
    P.AI_MANAGE,
    P.KNOWLEDGE_READ,
    P.KNOWLEDGE_MANAGE,
  ],

  HR: [
    P.USERS_READ,
    P.USERS_CREATE,
    P.USERS_UPDATE,
    P.USERS_INVITE,
    P.USERS_SUSPEND,
    P.DEPARTMENT_READ,
    P.TEAM_READ,
    P.INTERN_READ,
    P.INTERN_CREATE,
    P.INTERN_UPDATE,
    P.INTERN_PROFILE_READ,
    P.INTERN_PROFILE_UPDATE,
    P.INTERNSHIP_READ,
    P.INTERNSHIP_CREATE,
    P.INTERNSHIP_UPDATE,
    P.INTERNSHIP_COMPLETE,
    P.ONBOARDING_READ,
    P.ONBOARDING_MANAGE,
    P.ONBOARDING_COMPLETE,
    P.ATTENDANCE_READ,
    P.ATTENDANCE_CREATE,
    P.ATTENDANCE_UPDATE,
    P.ATTENDANCE_MANAGE,
    P.ATTENDANCE_CORRECTION_REVIEW,
    P.LEAVE_READ,
    P.LEAVE_APPROVE,
    P.LEAVE_REJECT,
    P.DOCUMENT_READ,
    P.DOCUMENT_UPLOAD,
    P.DOCUMENT_MANAGE,
    P.FEEDBACK_READ,
    P.FEEDBACK_CREATE,
    P.CHECKIN_READ,
    P.CHECKIN_REVIEW,
    P.PERFORMANCE_READ,
    P.PERFORMANCE_CREATE,
    P.PERFORMANCE_UPDATE,
    P.PERFORMANCE_REVIEW,
    P.CERTIFICATE_READ,
    P.CERTIFICATE_CREATE,
    P.CERTIFICATE_VERIFY,
    P.ANNOUNCEMENT_READ,
    P.ANNOUNCEMENT_CREATE,
    P.ANNOUNCEMENT_UPDATE,
    P.CALENDAR_READ,
    P.NOTIFICATION_READ,
    P.ANALYTICS_READ,
    P.AI_USE,
    P.KNOWLEDGE_READ,
  ],

  MANAGER: [
    P.USERS_READ,
    P.INTERN_READ,
    P.INTERN_PROFILE_READ,
    P.PROJECT_READ,
    P.PROJECT_CREATE,
    P.PROJECT_UPDATE,
    P.PROJECT_MANAGE_MEMBERS,
    P.TASK_READ,
    P.TASK_CREATE,
    P.TASK_UPDATE,
    P.TASK_ASSIGN,
    P.TASK_REVIEW,
    P.ATTENDANCE_READ,
    P.LEAVE_READ,
    P.DOCUMENT_READ,
    P.FEEDBACK_READ,
    P.FEEDBACK_CREATE,
    P.CHECKIN_READ,
    P.CHECKIN_CREATE,
    P.CHECKIN_REVIEW,
    P.PERFORMANCE_READ,
    P.PERFORMANCE_CREATE,
    P.PERFORMANCE_UPDATE,
    P.PERFORMANCE_REVIEW,
    P.CALENDAR_READ,
    P.CALENDAR_CREATE,
    P.CALENDAR_UPDATE,
    P.ANNOUNCEMENT_READ,
    P.NOTIFICATION_READ,
    P.LEARNING_READ,
    P.AI_USE,
    P.KNOWLEDGE_READ,
  ],

  MENTOR: [
    P.INTERN_READ,
    P.INTERN_PROFILE_READ,
    P.TASK_READ,
    P.PROJECT_READ,
    P.LEARNING_READ,
    P.COURSE_READ,
    P.FEEDBACK_READ,
    P.FEEDBACK_CREATE,
    P.CHECKIN_READ,
    P.CHECKIN_CREATE,
    P.ANNOUNCEMENT_READ,
    P.CALENDAR_READ,
    P.NOTIFICATION_READ,
    P.AI_USE,
    P.KNOWLEDGE_READ,
  ],

  INTERN: [
    P.INTERN_PROFILE_READ,
    P.INTERN_PROFILE_UPDATE,
    P.PROJECT_READ,
    P.TASK_READ,
    P.TASK_SUBMIT,
    P.ATTENDANCE_READ,
    P.ATTENDANCE_CREATE,
    P.ATTENDANCE_CORRECTION_REQUEST,
    P.LEAVE_READ,
    P.LEAVE_REQUEST,
    P.LEAVE_CANCEL,
    P.DOCUMENT_READ,
    P.DOCUMENT_UPLOAD,
    P.COURSE_READ,
    P.LEARNING_READ,
    P.FEEDBACK_READ,
    P.CHECKIN_READ,
    P.CHECKIN_CREATE,
    P.PERFORMANCE_READ,
    P.ANNOUNCEMENT_READ,
    P.NOTIFICATION_READ,
    P.CALENDAR_READ,
    P.CERTIFICATE_READ,
    P.AI_USE,
    P.KNOWLEDGE_READ,
  ],
}

export function permissionsForRole(role: string): Permission[] {
  return ROLE_PERMISSIONS[role as SystemRole] ?? []
}

export function roleHasPermission(role: string, permission: Permission): boolean {
  return permissionsForRole(role).includes(permission)
}

export function canAssignRole(actorRole: string, targetRole: string): boolean {
  const actorRank = ROLE_RANK[actorRole as SystemRole]
  const targetRank = ROLE_RANK[targetRole as SystemRole]
  if (actorRank === undefined || targetRank === undefined) return false
  if (actorRole === 'SUPER_ADMIN') return true
  return actorRank > targetRank
}
