/**
 * Audit action vocabulary. Names follow `resource.event`; security events
 * required by the specification map as documented (LOGIN_SUCCESS →
 * `auth.login_success`, …). Keep this list in sync with the audit log filter.
 */
export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'auth.login_success',
  LOGIN_FAILURE: 'auth.login_failure',
  LOGOUT: 'auth.logout',
  PASSWORD_RESET_REQUESTED: 'auth.password_reset_requested',
  PASSWORD_RESET_COMPLETED: 'auth.password_reset_completed',
  PASSWORD_CHANGED: 'auth.password_changed',
  EMAIL_VERIFIED: 'auth.email_verified',
  VERIFICATION_RESENT: 'auth.verification_resent',
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_REVOKED: 'invitation.revoked',
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_SUSPENDED: 'user.suspended',
  USER_REACTIVATED: 'user.reactivated',
  USER_DEACTIVATED: 'user.deactivated',
  ROLE_CHANGED: 'user.role_changed',
  PERMISSION_CHANGED: 'role.permission_changed',
  SESSION_REVOKED: 'session.revoked',
  ACCESS_DENIED: 'access.denied',
  INTERN_CREATED: 'intern.created',
  INTERN_UPDATED: 'intern.updated',
  MANAGER_ASSIGNED: 'intern.manager_assigned',
  MENTOR_ASSIGNED: 'intern.mentor_assigned',
  STATUS_CHANGED: 'intern.status_changed',
  INTERNSHIP_CREATED: 'internship.created',
  INTERNSHIP_UPDATED: 'internship.updated',
  ONBOARDING_CREATED: 'onboarding.created',
  ONBOARDING_COMPLETED: 'onboarding.completed',
  ONBOARDING_ITEM_COMPLETED: 'onboarding.item_completed',
  ONBOARDING_ITEM_UPDATED: 'onboarding.item_updated',
  POLICY_ACKNOWLEDGED: 'policy.acknowledged',
  TEMPLATE_CREATED: 'onboarding_template.created',
  TEMPLATE_UPDATED: 'onboarding_template.updated',
  DOCUMENT_UPLOADED: 'document.uploaded',
  DOCUMENT_DELETED: 'document.deleted',
  TASK_CREATED: 'task.created',
  TASK_UPDATED: 'task.updated',
  TASK_ASSIGNED: 'task.assigned',
  TASK_UNASSIGNED: 'task.unassigned',
  TASK_STATUS_CHANGED: 'task.status_changed',
  TASK_PRIORITY_CHANGED: 'task.priority_changed',
  TASK_DEADLINE_CHANGED: 'task.deadline_changed',
  TASK_DELETED: 'task.deleted',
  TASK_COMMENTED: 'task.commented',
  TASK_SUBMITTED: 'task.submitted',
  TASK_REVIEWED: 'task.reviewed',
  TASK_ATTACHMENT_ADDED: 'task.attachment_added',
  TASK_ATTACHMENT_REMOVED: 'task.attachment_removed',
  TASK_DEPENDENCY_CHANGED: 'task.dependency_changed',
  TASK_CHECKLIST_UPDATED: 'task.checklist_updated',
  TASK_TIME_LOGGED: 'task.time_logged',
  PROJECT_CREATED: 'project.created',
  PROJECT_UPDATED: 'project.updated',
  PROJECT_MEMBER_ADDED: 'project.member_added',
  PROJECT_MEMBER_REMOVED: 'project.member_removed',
  PROJECT_STATUS_CHANGED: 'project.status_changed',
  PROJECT_FILE_UPLOADED: 'project.file_uploaded',
  PROJECT_FILE_DELETED: 'project.file_deleted',
  MILESTONE_CREATED: 'milestone.created',
  MILESTONE_UPDATED: 'milestone.updated',
  MILESTONE_COMPLETED: 'milestone.completed',
  ATTENDANCE_CHECKED_IN: 'attendance.checked_in',
  ATTENDANCE_CHECKED_OUT: 'attendance.checked_out',
  ATTENDANCE_UPDATED: 'attendance.updated',
  ATTENDANCE_CORRECTION_REQUESTED: 'attendance.correction_requested',
  ATTENDANCE_CORRECTION_APPROVED: 'attendance.correction_approved',
  ATTENDANCE_CORRECTION_REJECTED: 'attendance.correction_rejected',
  LEAVE_REQUESTED: 'leave.requested',
  LEAVE_APPROVED: 'leave.approved',
  LEAVE_REJECTED: 'leave.rejected',
  LEAVE_CANCELLED: 'leave.cancelled',
  LEAVE_OVERLAP_OVERRIDDEN: 'leave.overlap_overridden',
  LEAVE_BALANCE_UPDATED: 'leave.balance_updated',
  LEAVE_TYPE_SAVED: 'leave_type.saved',
  DOCUMENT_VERIFIED: 'document.verified',
  DOCUMENT_REJECTED: 'document.rejected',
  DOCUMENT_REVIEW_STARTED: 'document.review_started',
  DOCUMENT_REPLACEMENT_REQUESTED: 'document.replacement_requested',
  DOCUMENT_EXPIRED: 'document.expired',
  DOCUMENT_TYPE_SAVED: 'document_type.saved',
  SENSITIVE_DOCUMENT_ACCESSED: 'document.sensitive_accessed',
  HR_REQUEST_CREATED: 'hr_request.created',
  HR_REQUEST_UPDATED: 'hr_request.updated',
  HR_REQUEST_COMMENTED: 'hr_request.commented',
  ANNOUNCEMENT_SAVED: 'announcement.saved',
  ANNOUNCEMENT_PUBLISHED: 'announcement.published',
  ANNOUNCEMENT_ARCHIVED: 'announcement.archived',
  HOLIDAY_SAVED: 'holiday.saved',
  HOLIDAY_DELETED: 'holiday.deleted',
  HR_SETTING_UPDATED: 'hr_settings.updated',
  PERSONAL_INFO_UPDATED: 'intern_profile.personal_updated',
  COMPENSATION_UPDATED: 'internship.compensation_updated',
  OFFBOARDING_STARTED: 'offboarding.started',
  OFFBOARDING_ITEM_UPDATED: 'offboarding.item_updated',
  EXPORT_GENERATED: 'export.generated',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export const SECURITY_ACTIONS: readonly string[] = Object.values(AUDIT_ACTIONS)
